version: '3.7'

services:
  backend:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    image: challenger/app
    command: ["./docker/wait-for-db.sh", "db", "./manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "trafficdb", "-U", "myuser" ]
      retries: 3
      timeout: 5s
networks:
    default:
      driver: bridge
volumes:
  pgsql:
    driver: local
